### ISSUE TITLE
Handle changes in domain registration

### ISSUE THREAD

**Issue by ayumi** [brave-intl/bat-ledger#42]
If you've registered potato.com and become a Brave publisher; and potato.com expires and Cate Camper registers it right away, contributions to potato.com should no longer flow to you.

eyeshade, as the canonical registration checker, should be the service which checks periodically.
it also needs communicate this info with publishers: https://github.com/brave-intl/publishers/issues/249

**Comment by mrose17** [comment]
i don't think there is any reliable way of determining when a domain changes ownership. presumably, we could look for the "updated date" in the registration entry, and if it changes, we could "do something, but i'm not sure what, because that doesn't necessarily mean there's a new owner.

alternatively, we can modify publishers to allow folks to re-verify the domain. there's no "real" reason (that i can think of) to not allow this.

any other ideas?

**Comment by ayumi** [comment]
i think we should record the WHOIS email of domains, and require reverification if that changes.

cc @evq

**Comment by ayumi** [comment]
and monitor registration expiry dates

**Comment by evq** [comment]
OBE see brave-intl/publishers#376
