### ISSUE TITLE
expose endpoint to create manual transactions from publishers app

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-ledger#518]
will be used to track manual publisher payments as part of - https://github.com/brave-intl/publishers/issues/1571

**Comment by nvonpentz** [comment]
I think the endpoint should be something like this, but am very open to suggestions:

```
PUT /v1/accounts/{account_type}/{owner_id}/transactions/{transaction_type}/{transactions_id}

{
    "amount": "50"
}
```

where  `account_type` is one of
```
['channel', 'owner', 'uphold', 'internal', 'payment_id']
```

and `transaction_type` is one of
```
['contribution', 'referral', 'contribution_settlement', 'referral_settlement', 'fees', 'scaleup', 'manual', 'ad', 'ad_settlement']
```

For the first implementation we will only support `owner` account types, and `manual` transaction_types`, and I think one per request probably sufficient rather than a bulk endpoint.

Using the information that Publishers supplied in the request, Eyeshade will enter into the transactions table

`id` - provided by publishers in uri
`created_at` - determined at the time the endpoint is hit
`description` - "manual payout to partner"
`transaction_type` - "manual", provided by publishers in the uri
`document_id` - null
`from_account_type` - "uphold"
`from_account` - brave settlement uphold wallet address (envar?)
`to_account_type` - owner, provided by publishers in uri
`to_account` - owner identifier, provided by publishers in uri
`amount` - amount, sent by publishers in request body
`channel` - null (?)
`settlement_currency` - null
`settlement_amount` - null
