### ISSUE TITLE
remove v1 legacy api support (bitcoin)

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-ledger#65]

**Comment by mrose17** [comment]
+1

**Comment by mrose17** [comment]
we had a bitcoin proof-of-concept a few years back. good for learning things. when we moved to BAT, we changed a lot of API endpoints from /v1 to /v2, since we couldn't get the same semantics. what this issue refers to is simply removing the BTC-only v1 API calls.  if you look at the admin page for the ledger, you'll see a number of calls tarting with /{apiV}/... that do either v1 (BTC proof-of-concept) or v2 (BAT Mercury).

**Comment by mmclau14** [comment]
alright, so just hard code all of the `/{apiV}/` to `/v2/` easy enough

**Comment by mrose17** [comment]
i think step 1 is to remove the /v1's that are accessible under /{apiV}

i think step 2 is to ask @evq whether we should get rid of /{apiV} or leave it. we might leave it, because we may have /v3 in the future. she will know.

**Comment by mmclau14** [comment]
cool cool. can do

**Comment by evq** [comment]
When doing some other cleanup I noticed that there are still v1 wallet endpoints, @maikelmclauflin can you remove them?
